---

- name: Setup gpg key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    keyring: /etc/apt/trusted.gpg.d/microsoft.gpg

- name: setup the apt repo
  apt_repository:
    repo: 'deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main'
    state: present
    filename: vscode

- name: install the apt-transport-https
  apt:
    name: apt-transport-https

- name: install vscode
  apt:
    name: code
    update_cache: True

